"""add_priority_and_issue_type_to_issues

Revision ID: 0c24616ede6f
Revises: 34348b79a231
Create Date: 2026-06-24 17:41:56.084334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c24616ede6f'
down_revision: Union[str, Sequence[str], None] = '34348b79a231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issuepriority'), nullable=False, server_default='MEDIUM'))
    op.add_column('issues', sa.Column('issue_type', sa.Enum('BUG', 'FEATURE', 'CHANGE_REQUEST', 'TRIAGE', name='issuetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'issue_type')
    op.drop_column('issues', 'priority')
    # ### end Alembic commands ###
